CREATE TABLE IF NOT EXISTS Batles(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
    WINrelativelyPl1 BOOLEAN NOT NULL,
  	Pl1Name varchar,
  	Pl1Id varchar,
  	Pl1card_1 TEXT NOT NULL,
    Pl1card_2 TEXT NOT NULL,
    Pl1card_3 TEXT NOT NULL,
    PL1card_4 TEXT NOT NULL,
    pL1card_5 TEXT NOT NULL,
    Pl1card_6 TEXT NOT NULL,
    Pl1card_7 TEXT NOT NULL,
    Pl1card_8 TEXT NOT NULL,
  	Pl1LVL INTEGER CHECK (Pl1LVL BETWEEN 1 AND 16) DEFAULT 1,
  	Pl1towersleft InTEGER CHECK (Pl1towersleft BETWEEN 0 and 3) default 0,
  	Pl2Name varchar,
  	Pl1Id varchar,
  	Pl2card_1 TEXT NOT NULL,
    Pl2card_2 TEXT NOT NULL,
    Pl2card_3 TEXT NOT NULL,
    Pl2card_4 TEXT NOT NULL,
    Pl2card_5 TEXT NOT NULL,
    Pl2card_6 TEXT NOT NULL,
    Pl2card_7 TEXT NOT NULL,
    Pl2card_8 TEXT NOT NULL,
  	Pl2LVL INTEGER CHECK (Pl2LVL BETWEEN 1 AND 16) DEFAULT 1,
  	Pl2towersleft InTEGER CHECK (Pl2towersleft BETWEEN 0 and 3) default 0
);
